export const CCSWITCH_PROVIDER_PRESETS = [
  {
    id: 'openrouter',
    name: 'OpenRouter',
    description: 'ccswitch 聚合平台预设',
    color: '#6366F1',
    initials: 'OR',
    baseUrl: 'https://openrouter.ai/api/v1',
    apiMode: 'chat_completions',
    requiresApiKey: true,
    apiKeyEnvVar: 'OPENROUTER_API_KEY',
    websiteUrl: 'https://openrouter.ai',
    apiKeyUrl: 'https://openrouter.ai/keys',
    models: [
      { id: 'anthropic/claude-opus-4-8', name: 'Claude Opus 4.8', contextLength: 1000000 },
      { id: 'anthropic/claude-sonnet-5', name: 'Claude Sonnet 5', contextLength: 1000000 },
      { id: 'anthropic/claude-haiku-4-5', name: 'Claude Haiku 4.5', contextLength: 200000 },
      { id: 'openai/gpt-5.5', name: 'GPT-5.5', contextLength: 400000 },
      { id: 'google/gemini-3.5-flash', name: 'Gemini 3.5 Flash', contextLength: 1000000 },
    ],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    description: 'ccswitch 国内/官方预设',
    color: '#4D6BFE',
    initials: 'DS',
    baseUrl: 'https://api.deepseek.com',
    apiMode: 'chat_completions',
    requiresApiKey: true,
    apiKeyEnvVar: 'DEEPSEEK_API_KEY',
    websiteUrl: 'https://platform.deepseek.com',
    apiKeyUrl: 'https://platform.deepseek.com/api_keys',
    models: [
      { id: 'deepseek-v4-flash', name: 'DeepSeek V4 Flash', contextLength: 1000000 },
      { id: 'deepseek-v4-pro', name: 'DeepSeek V4 Pro', contextLength: 1000000 },
    ],
  },
  {
    id: 'bailian',
    name: 'Bailian',
    description: 'ccswitch 国内/官方预设',
    color: '#624AFF',
    initials: 'BL',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    apiMode: 'chat_completions',
    requiresApiKey: true,
    apiKeyEnvVar: 'DASHSCOPE_API_KEY',
    websiteUrl: 'https://bailian.console.aliyun.com',
    models: [
      { id: 'qwen3-coder-plus', name: 'Qwen3 Coder Plus' },
      { id: 'qwen3-max', name: 'Qwen3 Max' },
    ],
  },
  {
    id: 'bailian_coding',
    name: 'Bailian For Coding',
    description: 'ccswitch 国内/官方预设',
    color: '#624AFF',
    initials: 'BC',
    baseUrl: 'https://coding.dashscope.aliyuncs.com/apps/anthropic',
    apiMode: 'anthropic_messages',
    requiresApiKey: true,
    apiKeyEnvVar: 'DASHSCOPE_API_KEY',
    websiteUrl: 'https://bailian.console.aliyun.com',
    models: [
      { id: 'qwen3-coder-plus', name: 'Qwen3 Coder Plus' },
      { id: 'qwen3-max', name: 'Qwen3 Max' },
    ],
  },
  {
    id: 'kimi',
    name: 'Kimi',
    description: 'ccswitch 国内/官方预设',
    color: '#6366F1',
    initials: 'KM',
    baseUrl: 'https://api.moonshot.cn/v1',
    apiMode: 'chat_completions',
    requiresApiKey: true,
    apiKeyEnvVar: 'KIMI_API_KEY',
    websiteUrl: 'https://platform.kimi.com?aff=cc-switch',
    models: [{ id: 'kimi-k2.7-code', name: 'Kimi K2.7 Code' }],
  },
  {
    id: 'kimi_coding',
    name: 'Kimi For Coding',
    description: 'ccswitch 国内/官方预设',
    color: '#6366F1',
    initials: 'KC',
    baseUrl: 'https://api.kimi.com/coding/',
    apiMode: 'anthropic_messages',
    requiresApiKey: true,
    apiKeyEnvVar: 'KIMI_CODING_API_KEY',
    websiteUrl: 'https://www.kimi.com/code/?aff=cc-switch',
    models: [{ id: 'kimi-for-coding', name: 'Kimi For Coding' }],
  },
  {
    id: 'zhipu_glm',
    name: 'Zhipu GLM',
    description: 'ccswitch 国内/官方预设',
    color: '#0F62FE',
    initials: 'GL',
    baseUrl: 'https://open.bigmodel.cn/api/coding/paas/v4',
    apiMode: 'chat_completions',
    requiresApiKey: true,
    apiKeyEnvVar: 'ZHIPUAI_API_KEY',
    websiteUrl: 'https://open.bigmodel.cn',
    apiKeyUrl: 'https://www.bigmodel.cn/claude-code?ic=RRVJPB5SII',
    models: [{ id: 'glm-5.1', name: 'GLM-5.1' }],
  },
  {
    id: 'zhipu_glm_en',
    name: 'Zhipu GLM en',
    description: 'ccswitch 国内/官方预设',
    color: '#0F62FE',
    initials: 'GE',
    baseUrl: 'https://api.z.ai/api/coding/paas/v4',
    apiMode: 'chat_completions',
    requiresApiKey: true,
    apiKeyEnvVar: 'ZHIPUAI_API_KEY',
    websiteUrl: 'https://z.ai',
    apiKeyUrl: 'https://z.ai/subscribe?ic=8JVLJQFSKB',
    models: [{ id: 'glm-5.1', name: 'GLM-5.1' }],
  },
  {
    id: 'stepfun',
    name: 'StepFun',
    description: 'ccswitch 国内/官方预设',
    color: '#005AFF',
    initials: 'SF',
    baseUrl: 'https://api.stepfun.ai/v1',
    apiMode: 'chat_completions',
    requiresApiKey: true,
    apiKeyEnvVar: 'STEPFUN_API_KEY',
    websiteUrl: 'https://platform.stepfun.ai',
    apiKeyUrl: 'https://platform.stepfun.ai/interface-key',
    models: [{ id: 'step-3.5-flash', name: 'Step 3.5 Flash' }],
  },
  {
    id: 'modelscope',
    name: 'ModelScope',
    description: 'ccswitch 聚合平台预设',
    color: '#624AFF',
    initials: 'MS',
    baseUrl: 'https://api-inference.modelscope.cn/v1',
    apiMode: 'chat_completions',
    requiresApiKey: true,
    apiKeyEnvVar: 'MODELSCOPE_API_KEY',
    websiteUrl: 'https://modelscope.cn',
    models: [{ id: 'ZhipuAI/GLM-5.1', name: 'ZhipuAI / GLM-5.1' }],
  },
  {
    id: 'longcat',
    name: 'Longcat',
    description: 'ccswitch 国内/官方预设',
    color: '#29E154',
    initials: 'LC',
    baseUrl: 'https://api.longcat.chat/openai/v1',
    apiMode: 'chat_completions',
    requiresApiKey: true,
    apiKeyEnvVar: 'LONGCAT_API_KEY',
    websiteUrl: 'https://longcat.chat/platform',
    apiKeyUrl: 'https://longcat.chat/platform/api_keys',
    models: [{ id: 'LongCat-2.0', name: 'LongCat 2.0' }],
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    description: 'ccswitch 国内/官方预设',
    color: '#FF6B6B',
    initials: 'MM',
    baseUrl: 'https://api.minimaxi.com/v1',
    apiMode: 'chat_completions',
    requiresApiKey: true,
    apiKeyEnvVar: 'MINIMAX_API_KEY',
    websiteUrl: 'https://platform.minimaxi.com',
    apiKeyUrl: 'https://platform.minimaxi.com/subscribe/coding-plan',
    models: [{ id: 'MiniMax-M2.7', name: 'MiniMax M2.7' }],
  },
  {
    id: 'minimax_en',
    name: 'MiniMax en',
    description: 'ccswitch 国内/官方预设',
    color: '#FF6B6B',
    initials: 'ME',
    baseUrl: 'https://api.minimax.io/v1',
    apiMode: 'chat_completions',
    requiresApiKey: true,
    apiKeyEnvVar: 'MINIMAX_API_KEY',
    websiteUrl: 'https://platform.minimax.io',
    apiKeyUrl: 'https://platform.minimax.io/subscribe/coding-plan',
    models: [{ id: 'MiniMax-M2.7', name: 'MiniMax M2.7' }],
  },
  {
    id: 'bailing',
    name: 'BaiLing',
    description: 'ccswitch 国内/官方预设',
    color: '#14B8A6',
    initials: 'BL',
    baseUrl: 'https://api.tbox.cn/api/anthropic',
    apiMode: 'anthropic_messages',
    requiresApiKey: true,
    apiKeyEnvVar: 'BAILING_API_KEY',
    websiteUrl: 'https://alipaytbox.yuque.com/sxs0ba/ling/get_started',
    models: [{ id: 'Ling-2.5-1T', name: 'Ling 2.5 1T' }],
  },
  {
    id: 'siliconflow',
    name: 'SiliconFlow',
    description: 'ccswitch 聚合平台预设',
    color: '#6E29F6',
    initials: 'SF',
    baseUrl: 'https://api.siliconflow.cn/v1',
    apiMode: 'chat_completions',
    requiresApiKey: true,
    apiKeyEnvVar: 'SILICONFLOW_API_KEY',
    websiteUrl: 'https://siliconflow.cn',
    apiKeyUrl: 'https://cloud.siliconflow.cn/i/YflgU2Ve',
    models: [{ id: 'Pro/MiniMaxAI/MiniMax-M2.7', name: 'Pro / MiniMax M2.7' }],
  },
  {
    id: 'siliconflow_en',
    name: 'SiliconFlow en',
    description: 'ccswitch 聚合平台预设',
    color: '#111827',
    initials: 'SE',
    baseUrl: 'https://api.siliconflow.com/v1',
    apiMode: 'chat_completions',
    requiresApiKey: true,
    apiKeyEnvVar: 'SILICONFLOW_API_KEY',
    websiteUrl: 'https://siliconflow.com',
    apiKeyUrl: 'https://cloud.siliconflow.cn/i/YflgU2Ve',
    models: [{ id: 'MiniMaxAI/MiniMax-M2.7', name: 'MiniMax M2.7' }],
  },
  {
    id: 'together',
    name: 'Together AI',
    description: 'ccswitch 聚合平台预设',
    color: '#0F6FFF',
    initials: 'TA',
    baseUrl: 'https://api.together.xyz/v1',
    apiMode: 'chat_completions',
    requiresApiKey: true,
    apiKeyEnvVar: 'TOGETHER_API_KEY',
    websiteUrl: 'https://together.ai',
    apiKeyUrl: 'https://api.together.ai/settings/api-keys',
    models: [
      { id: 'Qwen/Qwen3-Coder-480B-A35B-Instruct', name: 'Qwen3 Coder 480B', contextLength: 262144 },
      { id: 'deepseek-ai/DeepSeek-V3.2', name: 'DeepSeek V3.2', contextLength: 64000 },
      { id: 'meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8', name: 'Llama 4 Maverick', contextLength: 131072 },
    ],
  },
  {
    id: 'nous',
    name: 'Nous Research',
    description: 'ccswitch 官方预设',
    color: '#7C3AED',
    initials: 'NR',
    baseUrl: 'https://inference-api.nousresearch.com/v1',
    apiMode: 'chat_completions',
    requiresApiKey: true,
    apiKeyEnvVar: 'NOUS_API_KEY',
    websiteUrl: 'https://nousresearch.com',
    apiKeyUrl: 'https://portal.nousresearch.com/',
    models: [
      { id: 'Hermes-4-405B', name: 'Hermes 4 405B', contextLength: 131072 },
      { id: 'Hermes-4-70B', name: 'Hermes 4 70B', contextLength: 131072 },
    ],
  },
  {
    id: 'ark_agentplan',
    name: '火山Agentplan',
    description: 'ccswitch 国内/官方预设',
    color: '#3370FF',
    initials: 'VA',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/coding',
    apiMode: 'anthropic_messages',
    requiresApiKey: true,
    apiKeyEnvVar: 'ARK_API_KEY',
    websiteUrl: 'https://www.volcengine.com/product/ark',
    models: [{ id: 'ark-code-latest', name: 'Ark Code Latest' }],
  },
  {
    id: 'doubao_seed',
    name: 'DouBaoSeed',
    description: 'ccswitch 国内/官方预设',
    color: '#3370FF',
    initials: 'DB',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/compatible',
    apiMode: 'anthropic_messages',
    requiresApiKey: true,
    apiKeyEnvVar: 'ARK_API_KEY',
    websiteUrl: 'https://www.volcengine.com/product/doubao',
    models: [{ id: 'doubao-seed-2-1-pro-260628', name: 'Doubao Seed 2.1 Pro' }],
  },
  {
    id: 'aihubmix',
    name: 'AiHubMix',
    description: 'ccswitch 聚合平台预设',
    color: '#006FFB',
    initials: 'AH',
    baseUrl: 'https://aihubmix.com/v1',
    apiMode: 'chat_completions',
    requiresApiKey: true,
    apiKeyEnvVar: 'AIHUBMIX_API_KEY',
    websiteUrl: 'https://aihubmix.com',
    models: [{ id: 'gpt-5.5', name: 'GPT-5.5' }],
  },
  {
    id: 'therouter',
    name: 'TheRouter',
    description: 'ccswitch 聚合平台预设',
    color: '#6366F1',
    initials: 'TR',
    baseUrl: 'https://api.therouter.ai/v1',
    apiMode: 'chat_completions',
    requiresApiKey: true,
    apiKeyEnvVar: 'THEROUTER_API_KEY',
    websiteUrl: 'https://therouter.ai',
    apiKeyUrl: 'https://dashboard.therouter.ai',
    models: [
      { id: 'openai/gpt-5.5', name: 'GPT-5.5' },
      { id: 'openai/gpt-5.4-mini', name: 'GPT-5.4 mini' },
      { id: 'openai/gpt-5.4-nano', name: 'GPT-5.4 nano' },
    ],
  },
  {
    id: 'novita',
    name: 'Novita AI',
    description: 'ccswitch 聚合平台预设',
    color: '#624AFF',
    initials: 'NA',
    baseUrl: 'https://api.novita.ai/v3/openai',
    apiMode: 'chat_completions',
    requiresApiKey: true,
    apiKeyEnvVar: 'NOVITA_API_KEY',
    websiteUrl: 'https://novita.ai',
    models: [{ id: 'zai-org/glm-5.1', name: 'Zai-Org / GLM-5.1' }],
  },
  {
    id: 'nvidia',
    name: 'Nvidia',
    description: 'ccswitch 聚合平台预设',
    color: '#76B900',
    initials: 'NV',
    baseUrl: 'https://integrate.api.nvidia.com',
    apiMode: 'chat_completions',
    requiresApiKey: true,
    apiKeyEnvVar: 'NVIDIA_API_KEY',
    websiteUrl: 'https://build.nvidia.com',
    apiKeyUrl: 'https://build.nvidia.com/settings/api-keys',
    models: [{ id: 'moonshotai/kimi-k2.5', name: 'Moonshot Kimi K2.5' }],
  },
  {
    id: 'xiaomi_mimo',
    name: 'Xiaomi MiMo',
    description: 'ccswitch 国内/官方预设',
    color: '#FF6900',
    initials: 'XM',
    baseUrl: 'https://api.xiaomimimo.com/v1',
    apiMode: 'chat_completions',
    requiresApiKey: true,
    apiKeyEnvVar: 'XIAOMI_MIMO_API_KEY',
    websiteUrl: 'https://platform.xiaomimimo.com',
    models: [{ id: 'mimo-v2.5-pro', name: 'MiMo v2.5 Pro' }],
  },
] as const
